language: python
python:
- 3.7.4
install:
- pip install codecov
- pip install pytest-cov
script:
- pytest
- coverage run -m pytest
after_success:
- codecov
after_script:
- cd /src
deploy:
  provider: pypi
  user: GenesisCoast
  password:
    secure: q/FO8jipNgbifwRfQfORiEPMzMOiUECFi3veKO2EXUlwxD3UdwY9IL1MZcqtr6PPtepXdAU48W3oqRMcUzn7XVQatDlqBLzKOlEZ3TFYJdfpWIh8EdDWQ3bqWo7ZDtPzrYqc5islL30e9MbTwbfo8a99qLhpwjAG9keirKP5ppv6LaR6v2COswE+Itjf8VQbUWmR9sB6S4+91m8ZgnSP0KYXd6bDuddDWSHJ9YET16dNolLcfdDvq2LVIF9yhQAa6a7V5xOp8ZZAvIFkABSMGX6ib+2HbA++Zd4GhLX46UdC1+rMuzQCruVQ1KAcyUVSHFHaBvLIc7ZRqqnpykUmWGdxLrD2xwrUXfo/RuY6DknO7dVvp2bP/CMxN8MY6jmJc2Pi/ImET5jw048orWJnMWkgecoN5mAvJZxBiNfPrCbDMZyPvENMkEl/tdPfuSbICsUBZIBV+SyRsRVYqEM3FgIBmqOjhrEN2HJReArsYvzR6yD034OBSh7utvifQzFk8xhMUreV0TlsIHMu1kPR9AKa/B6Xoh5b5KRr2u4GjqTiOHDiYtTy+gOybxhrQ95mRquMurjAb8CbEXSnhB5+nhUKReXGAJuWrtbb6Rwt34Yzpl+u+o2/ZbkHBH1A6jKnebQca42hpLyg2ozmzo0Jn1LNn0Yg26Yj3djjTluX5wo=
