language: python
python:
  - "3.7.4"
  
install:
  - pip install pytest-cov
  
script: 
  - pytest
  - pytest --cov=conditions-py tests/

env:
  - CODECOV_TOKEN="a3ea37cf-302f-4eb5-8dbd-fc4cb31e689b"

after_success:
    - codecov
