language: python
python:
- 3.7.4
install:
- pip install codecov
- pip install pytest-cov
script:
- pytest
- coverage run -m pytest
after_success:
- codecov
after_script:
- cd /src
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: GenesisCoast
  password:
    secure: "S3cvvSyzLcyYexKg6bvNTMSDYMSsaD/WvAfdS2zEl3DvNxi6nd3+dSlI1YgqYfuYbixv2bQ2h8wO2Ea8NcoDRbfIWSPjlvQcOb8SBxhoPGpwarom1XNX4yubYaHb+mUXXNDItR3vjcVUn4Qk0Wqnsvhd8EuwiItCJNoWFuRjX47V3JA10Ti3Oh2T6G85UqnDwMIyl2B0/vqhZaWQSYTMXaYFl3B7hKzvDEesExzpL0vnsqnsYV+tmoY4vrS0hyzUKQ8Vv6TWQabP0XUMsL8gpwZ5UN8J9BlUveExyw4HPoScYa6WmBHCgu67YXYtbd0WXTUZxOQRdydVJZ/wYC2qem0m6S5LZRmSUoeTOdmUH7ccCgC8nHuvSPtrfFY6KDVN27BO5txRi/lcLuBfBcfqfdOaPtxo96NqJ+7+vv+lcVtaG+rWBZTukk+rtEb39tqTu417LKrGIc/gevNw5UgcjvWevCsfmP91kiGA3qEb1Daj4nTTiZFQus+ptWBsxBSIcx0nSqsxfScLncG6zM0X3KmvFzqUDOpJ3hGmJEHR8LXQU9ANWBulFnGQOdpD6tzVOEmIDJSt41Z4fmBOKHbGP/Ima3d4oh5B35BVt8toguGQ25TvseXfvPK/AtfQWr67fy4eXGf3DOfdNPcc9uTU2OBfrC0q52FzLXTJsTi8S28="