language: python
python:
- 3.7.4
install:
- pip install codecov
- pip install pytest-cov
script:
- pytest
- coverage run -m pytest
after_success:
- codecov
after_script:
- cd /src
deploy:
  provider: pypi
  user: GenesisCoast
  password:
    secure: VPJDZdE59uBkkgbYovMbNBA7z1Pk++ZwSHnh+A6L1HPa8VaCs5jfYXtnKk7/PpkXsuRwfGFdMEBXoOONaJh9qUCVTPsPZYWtUcPaEH5bzDhSSvGhlWK2YGsaQsBPqQD6/REw5hr2M0XAMidSZdzQhRkyFnEkKag2e5UBca2/kouq2xwY8U30Zyr4AgyJ8YIBerLO+2jFzC1sITuUSNCfZU6eG3F5S+6ZpttL6yIr9XTIXqA56198/r1TXMn7scHPF2Sq1RvJGTBOccBUH2ruQNDTNi8tUDUSqIRmmjYk3EsXMZfjydKWMI1TgUCM/V+gn2VQHBlQhO4ZuA9dl+T9OlPhCVkHj3tmd91HI2HorovmeCY+AEQ3yJYyQplvcDYb0uW5WHpESFFBS2leg4/wBERF2UyrTswGUis6xGezPA2qU8eY54ZLsHXkb1gpHE+gab7xvMncaPNfpLMXwLxgB4uuOOXiDNo0blXambh+k3C9GfYf/avTvAisU2xajTdTQYa+TiPQ9kfmz6BDYfBs+92r0aLecKUN6uo15Fve1+X++Vy7lJqvePZxtrHHmO0HQ7zlfo5hXSygI15PI7WKoaIekTQx/mO1QOCbNWYFg4kDls8UzPUDkb1aXvSKMYdQePwkeQWE7t6xO7IY/ZLwSLNhcEA1RzQ1bNb+a3KT+oE=
