language: python
python:
  - "3.7.4"
  
install:
  - pip install codecov
  - pip install pytest-cov
  
script: 
  - pytest
  - coverage run -m pytest

env:
  - CODECOV_TOKEN="a3ea37cf-302f-4eb5-8dbd-fc4cb31e689b"

after_success:
    - codecov
